"use client";

import jsPDF from "jspdf";
import { Button } from "@/components/ui/button";

export function ExportReportButton() {
  function exportPdf() {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text("CampusCalm - Stress Prediction Report", 14, 18);
    doc.setFontSize(12);
    doc.text("This generated report summarizes stress prediction history and wellness recommendations.", 14, 30);
    doc.text("Generated by CampusCalm Dashboard", 14, 40);
    doc.save("campuscalm-report.pdf");
  }

  return <Button onClick={exportPdf}>Export PDF Report</Button>;
}
